nacos:
  server_addr: 192.168.50.62:8848
  namespace: null
  data_id: langgraph-agent-starter.local.yaml
  group: DEFAULT_GROUP
  backend: sdk_v2
  polling_interval_seconds: 5
  sdk_log_path: logs/nacos.log
  sdk_log_level: INFO
  username: nacos
  password: nacos

app:
  name: langgraph-agent-starter

server:
  host: 0.0.0.0
  port: 8080
  workers: 8

logging:
  dir: logs
  level: INFO
  max_bytes: 104857600
  backup_count: 7

langgraph:
  checkpointer:
    backend: memory
    redis_url: redis://127.0.0.1:6379/0

langfuse:
  enabled: false
  host: https://us.cloud.langfuse.com
  public_key: your-langfuse-public-key
  secret_key: your-langfuse-secret-key

api:
  auth:
    enabled: true
    sys_codes:
      - demo-system
      - real-system

workflow_configs:
  defaults:
    local_dir: configs/workflows
    nacos:
      enabled: true
      group: LANGGRAPH_AGENT_STARTER_WORKFLOW
      backend: sdk_v2
      polling_interval_seconds: 5
      data_id_template: "langgraph-agent-starter.workflow.{workflow}.yaml"
  items:
    demo-chat:
      local_path: configs/workflows/demo-chat.yaml
      nacos:
        data_id: langgraph-agent-starter.workflow.demo-chat.yaml
    demo-hitl:
      local_path: configs/workflows/demo-hitl.yaml
      nacos:
        data_id: langgraph-agent-starter.workflow.demo-hitl.yaml
    demo-summary:
      local_path: configs/workflows/demo-summary.yaml
      nacos:
        data_id: langgraph-agent-starter.workflow.demo-summary.yaml
